server:
  port: 8762
spring:
  application:
    name: gateway-server
  zipkin:
    base-url: http://localhost:8804
zuul:
 host: 
  connect-timeout-millis: 10000
  socket-timeout-millis: 60000
 routes:
  hades-service-app:
   path:/hades-service-app/**
    serviceId=hades-service-app
  hades-service-base:
   path:/hades-service-base/**
    serviceId=hades-service-base   
  hades-service-platform:
   path:/hades-service-platform/**
    serviceId=hades-service-platform  
eureka:
  client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 

ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000  

