spring:
 application:
  name: discovery-server
  
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true   #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/